### ISSUE TITLE
Bug: Error when validateAgainstSchema is run

### ISSUE THREAD

**Issue by cjhensen** [segmentio/typewriter#281] opened 2022-12-22 15:02 UTC
# Thanks for taking the time to contribute to Typewriter!

Hey @oscb! Thanks for fixing the usage of `validateAgainstSchema` ([this issue](https://github.com/segmentio/typewriter/issues/271))!

Running on localhost with my analytics library generated in "development" mode, I see errors being thrown on schema validation:
![image](https://user-images.githubusercontent.com/6188364/209161602-b5399989-7d13-4c6e-83fd-462b02e1d4ee.png)

Looking at the schema defined in each tracking function, such as:
```
    const schema = {"$id":"Thing viewed","$schema":"http://json-schema.org/draft-07/schema#","description":"A thing notification was viewed by the member","properties":{"component":{"$id":"/properties/component","description":"","type":"string"},"name":{"$id":"/properties/name","description":"e.g. \"Contact us button\"","type":"string"},"pathName":{"$id":"/properties/pathName","description":"","type":"string"},"title":{"$id":"/properties/title","description":"title in the Thing","type":"string"},"url":{"$id":"/properties/url","description":"","type":"string"}},"required":["component","name","pathName","url","title"],"type":"object"};
```

It's unclear what the `data.$id` is referring to in the error. Is it the `"$id": "Thing viewed"`?
Furthermore, my event properties in the code match those define in the tracking plan, so not sure how to resolve this issue.

Given the errors, I wanted to disable runtime validation, so I set `runtime-typecheck` to `false` in `typewriter.yml`, however the `validateAgainstSchema` function is still called for each tracking function after re-generating the client.

**Comment by oscb** [comment] 2023-01-09 23:58
Hey @cjhensen sorry for the long wait, I was out and couldn't get to this until today.
So the validations actually are the difference between `development` and `production` mode. If you make a build for `production` (`build --mode prod`) it will remove them

The problem is on our end, the schema id shouldn't have spaces: `"$id": "Thing viewed"` so either our servers or Typewriter need to sanitize those (pushing a fix for Typewriter for now, until we get that fixed on the server). Sorry for the inconvenience!

**Comment by richessler** [comment] 2023-01-13 05:28
@oscb thanks for the answer, I'm not seeing that as the issue on my end. I'm running into the exact same issue as @cjhensen but my analytics file wasn't generated with spaces. Any other thoughts?

**Closed** 2023-01-31 00:14 UTC
