### ISSUE TITLE
'npx typewriter init' fails with error 'setRawMode is not a function'

### ISSUE THREAD

**Issue by DominikFra** [segmentio/typewriter#139] opened 2020-09-02 12:56 UTC
I'm trying to use typewriter
When trying to create a typewiter.yml with the command `npx typewriter init` I am getting the error message:

  ✖ Error: An unexpected error occurred.
   → setRawMode is not a function

I'm using MacOS
node: v12.18.3
npx: 6.14.6
typewriter: 7.1.0

**Comment by jedvalmar** [comment] 2020-09-22 23:20
@DominikFra  I had the same issue and was able to make typewriter work by using `npx typewriter@next init` instead.

Using MacOS
node: v12.18.4
npx: 6.14.6
typewriter: 7.1.0

**Comment by Duder-onomy** [comment] 2021-03-08 23:47
Same issue, 
@jedvalmar work-around does not fix things for me. 

Osx
Node: 15.11.0
npx: 7.6.0
typewriter: 7.4.1

**Comment by vianch** [comment] 2021-03-09 21:01
Same here
OSX
node 14.15.5
typewriter 741

**Comment by Duder-onomy** [comment] 2021-03-09 23:09
Ok, mine just started working.  Here is what changed

* We didn't have ANY API tokens configured in the workspace, so we configured 1, the same I used to successfully run `npx typewriter init` later.   ...I suppose I expected to be prompted to make a token in the segment gui? 
* I manually created this `typewriter.yml` 

```
scripts:
  token: <1234ABCD123ABC12AB1A>
client:
  sdk: analytics.js
  language: typescript
trackingPlans:
  - id: <ABCDEFG......>
    workspaceSlug: <sluglife>
    path: ./analytics
```

After those 2 changes, I was able to run `npx typewriter init`

**Comment by ravioday** [comment] 2021-03-30 19:59
Same issue here , `npx typewriter init` fails with the above mentioned error. see img below: 

<img width="588" alt="Screen Shot 2021-03-30 at 3 56 30 PM" src="https://user-images.githubusercontent.com/5224363/113048713-d58bb680-9170-11eb-9888-e3d02a3a5aed.png">

**Comment by singhprincejeet** [comment] 2021-06-11 18:33
Same issue here, none of the above mentioned work arounds worked.

Mac OS 11.4
yarn: 1.21.1
typewriter: 7.4.1

**Comment by alanjcharles** [comment] 2021-07-07 17:28
Hi @singhprincejeet  @ravioday I'm not able to replicate this I'm afraid. Please reach out to friends@segment.com for more troubleshooting support. Closing for now.

**Closed by alanjcharles** 2021-07-07 17:28 UTC

**Comment by joeyorlando** [comment] 2021-07-28 17:23
still getting this error as well..

Mac OS: 11.4
yarn: 1.22.10
typewriter: 7.4.1

**Comment by dwjohnston** [comment] 2021-09-01 01:03
@alanjcharles  I'm getting this error. Can you please up reopen.

**Comment by dwjohnston** [comment] 2021-09-01 01:06
The stack trace I get is: 

```
TypeError: setRawMode is not a function
    at SelectInput.componentDidMount (/Users/djohnston/git/typewriter/node_modules/ink-select-input/build/SelectInput.js:161:5)
    at jg (/Users/djohnston/git/typewriter/node_modules/typewriter/node_modules/react-reconciler/cjs/react-reconciler.production.min.js:152:160)
    at exports.unstable_runWithPriority (/Users/djohnston/git/typewriter/node_mo

  ✖ Error: An unexpected error occurred.
   → setRawMode is not a function

  If you are unable to resolve this issue, open an issue on GitHub. Please inclu
de
   that you are using version 7.4.1 of Typewriter.
```

**Comment by dwjohnston** [comment] 2021-09-01 01:07
I wonder if this is related? https://github.com/vadimdemedes/ink-select-input/issues/18

**Comment by dwjohnston** [comment] 2021-09-01 02:01
It looks like the issue is react 17. Works on react 16.
